version: '3.4'

services:
  webclientconsul:
    image: ${DOCKER_REGISTRY-}webclientconsul
    build:
      context: .
      dockerfile: WebClientConsul/Dockerfile
    container_name: webclientconsul
    networks:
      - default_network    
networks:
  default_network:
    external: true      