version: '3.4'

services:
  webclientconsul:
    image: 10.0.18.30:8082/compuletra.webclient:latest
    build:
      context: .
      dockerfile: WebClientConsul/Dockerfile
    container_name: webclientconsul


networks:
  default:
    external:
      name: compuletra