version: '3.2'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      # POSTGRES_DB: jhipster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  gateway-app:
    container_name: gateway
    image: gateway
    depends_on:
      - db
    build:
      context: ../
      dockerfile: src/Gateway/Dockerfile
    ports:
      - 5050:80
